name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      - name: Lints Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
